# Clés d'identification SonarCloud
sonar.organization=wassimyaich
sonar.projectKey=wassimyaich_AI-Agent-Project

# Inclusion et exclusion des fichiers pour l'analyse du code
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/test_*.py
sonar.exclusions=**/test_*.py, documents/**, venv/**

# Chemin vers le rapport de couverture généré par pytest-cov
sonar.python.coverage.reportPaths=coverage.xml